// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: task_log.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_LOG_TYPE_FINISH LogType = 0
	LogType_LOG_TYPE_CREATE LogType = 1
	LogType_LOG_TYPE_DELETE LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "LOG_TYPE_FINISH",
		1: "LOG_TYPE_CREATE",
		2: "LOG_TYPE_DELETE",
	}
	LogType_value = map[string]int32{
		"LOG_TYPE_FINISH": 0,
		"LOG_TYPE_CREATE": 1,
		"LOG_TYPE_DELETE": 2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_log_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_task_log_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_task_log_proto_rawDescGZIP(), []int{0}
}

type TaskLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogUUID       string                 `protobuf:"bytes,1,opt,name=LogUUID,proto3" json:"LogUUID,omitempty"`
	LogType       LogType                `protobuf:"varint,2,opt,name=LogType,proto3,enum=pet_api.LogType" json:"LogType,omitempty"`
	UserUUID      string                 `protobuf:"bytes,3,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	TaskUUID      string                 `protobuf:"bytes,4,opt,name=TaskUUID,proto3" json:"TaskUUID,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLog) Reset() {
	*x = TaskLog{}
	mi := &file_task_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLog) ProtoMessage() {}

func (x *TaskLog) ProtoReflect() protoreflect.Message {
	mi := &file_task_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLog.ProtoReflect.Descriptor instead.
func (*TaskLog) Descriptor() ([]byte, []int) {
	return file_task_log_proto_rawDescGZIP(), []int{0}
}

func (x *TaskLog) GetLogUUID() string {
	if x != nil {
		return x.LogUUID
	}
	return ""
}

func (x *TaskLog) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_LOG_TYPE_FINISH
}

func (x *TaskLog) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *TaskLog) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *TaskLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_task_log_proto protoreflect.FileDescriptor

const file_task_log_proto_rawDesc = "" +
	"\n" +
	"\x0etask_log.proto\x12\apet_api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\aTaskLog\x12\x18\n" +
	"\aLogUUID\x18\x01 \x01(\tR\aLogUUID\x12*\n" +
	"\aLogType\x18\x02 \x01(\x0e2\x10.pet_api.LogTypeR\aLogType\x12\x1a\n" +
	"\bUserUUID\x18\x03 \x01(\tR\bUserUUID\x12\x1a\n" +
	"\bTaskUUID\x18\x04 \x01(\tR\bTaskUUID\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*H\n" +
	"\aLogType\x12\x13\n" +
	"\x0fLOG_TYPE_FINISH\x10\x00\x12\x13\n" +
	"\x0fLOG_TYPE_CREATE\x10\x01\x12\x13\n" +
	"\x0fLOG_TYPE_DELETE\x10\x02B\n" +
	"Z\bpkg/taskb\x06proto3"

var (
	file_task_log_proto_rawDescOnce sync.Once
	file_task_log_proto_rawDescData []byte
)

func file_task_log_proto_rawDescGZIP() []byte {
	file_task_log_proto_rawDescOnce.Do(func() {
		file_task_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_log_proto_rawDesc), len(file_task_log_proto_rawDesc)))
	})
	return file_task_log_proto_rawDescData
}

var file_task_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_task_log_proto_goTypes = []any{
	(LogType)(0),                  // 0: pet_api.LogType
	(*TaskLog)(nil),               // 1: pet_api.TaskLog
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_task_log_proto_depIdxs = []int32{
	0, // 0: pet_api.TaskLog.LogType:type_name -> pet_api.LogType
	2, // 1: pet_api.TaskLog.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_task_log_proto_init() }
func file_task_log_proto_init() {
	if File_task_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_log_proto_rawDesc), len(file_task_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_log_proto_goTypes,
		DependencyIndexes: file_task_log_proto_depIdxs,
		EnumInfos:         file_task_log_proto_enumTypes,
		MessageInfos:      file_task_log_proto_msgTypes,
	}.Build()
	File_task_log_proto = out.File
	file_task_log_proto_goTypes = nil
	file_task_log_proto_depIdxs = nil
}
